import fs from 'node:fs';
import path from 'node:path';
import { findRoot, run, runShell, commandExists, readJson, writeJson, writeText, now } from './lib.mjs';
const root=findRoot();
const checks=[];
const add=(name,ok,detail)=>checks.push({name,ok,detail});
add('package.json',fs.existsSync(path.join(root,'package.json')),'Projektroot');
add('CLAUDE import',fs.existsSync(path.join(root,'CLAUDE.md'))&&fs.readFileSync(path.join(root,'CLAUDE.md'),'utf8').includes('@company/CLAUDE_PRODUCT_COMPANY.md'),'verbindliche Firmenanweisung');
add('company config',fs.existsSync(path.join(root,'company','config','company.config.json')),'Konfiguration');
const requiredAgents=['mission-director','product-strategist','user-researcher','product-experience-architect','data-architecture-lead','security-performance-reviewer','product-engineer','qa-red-team','release-operations','independent-verifier'];
for(const a of requiredAgents) add(`agent:${a}`,fs.existsSync(path.join(root,'.claude','agents',`company-${a}.md`)),'ausführbarer Projektagent');
add('settings.json',fs.existsSync(path.join(root,'.claude','settings.json')),'Hook-Konfiguration');
add('claude CLI',await commandExists('claude',root),'Claude Code ausführbar');
add('git',await commandExists('git',root),'Versionskontrolle');
add('node>=18',Number(process.versions.node.split('.')[0])>=18,process.versions.node);
add('vercel',await commandExists('vercel',root),'optional; erforderlich für automatisches Preview');
add('vercel linked',fs.existsSync(path.join(root,'.vercel','project.json')),'optional; Projektverknüpfung');
add('supabase CLI',await commandExists('supabase',root),'optional; erforderlich für Remote-Migration');
const report={generatedAt:now(),root,readyForMission:checks.filter(x=>!['vercel','vercel linked','supabase CLI'].includes(x.name)).every(x=>x.ok),checks};
const dir=path.join(root,'company','reports'); fs.mkdirSync(dir,{recursive:true});
writeJson(path.join(dir,'doctor.json'),report);
let md=`# Product Company Doctor\n\nErstellt: ${report.generatedAt}\n\n| Prüfung | Status | Detail |\n|---|---|---|\n`;
for(const c of checks) md+=`| ${c.name} | ${c.ok?'PASS':'FAIL'} | ${String(c.detail).replaceAll('|','/')} |\n`;
md+=`\n**Missionsbereit:** ${report.readyForMission?'JA':'NEIN'}\n`;
writeText(path.join(dir,'doctor.md'),md);
console.log(md);
process.exit(report.readyForMission?0:2);
