export type CustomerListItem = { id: string; customerNumber: string; name: string; type: string; city: string | null };
export type CustomersViewState = { kind: "loading" } | { kind: "denied" | "error" | "conflict"; message: string } | { kind: "data"; customers: CustomerListItem[] };
export type CustomerOrderItem = { id: string; orderNumber: string; title: string; station: string; status: string; dueAt: string | null; version: number };
export type CustomerCardModel = {
  id: string;
  customerNumber: string | null;
  name: string;
  companyName: string | null;
  type: string;
  contactPerson: string | null;
  email: string | null;
  phone: string | null;
  address: string | null;
  zipCode: string | null;
  city: string | null;
  country: string | null;
  classification: string | null;
  notes: string | null;
  tags: string[];
  createdAt: string;
  updatedAt: string;
  orderCount: number;
  wareImHausCount: number;
  orders: CustomerOrderItem[];
};
export type CustomerCardState = { kind: "loading" } | { kind: "denied" | "not-found" | "error" | "conflict"; message: string } | { kind: "data"; card: CustomerCardModel };
