// src/lib/warnings/ruleRegistry.ts
// Regelkatalog V1 — 20+ Regeln aus Spec 10 Kapitel 7
import type { WarningRule } from "@/types/warnings";

const now = new Date().toISOString();

export const WARNING_RULES: WarningRule[] = [
  // ── Domain: login ────────────────────────────────────────────────────────
  {
    id: "login-01",
    code: "LOGIN_BRUTEFORCE",
    domain: "login",
    severity: "critical",
    trigger: "threshold",
    title: "Zu viele PIN-Fehlversuche",
    description: "5 PIN-Fehlversuche innerhalb von 2 Minuten",
    expression: "pinFailures >= 5",
    cooldownMinutes: 10,
    proposedAction: "Kachel temporär sperren",
    routeOnClick: "/settings/users",
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "login-02",
    code: "SESSION_INACTIVE_30M",
    domain: "login",
    severity: "info",
    trigger: "timeout",
    title: "Sitzung inaktiv",
    description: "Nutzer war länger als 30 Minuten inaktiv",
    expression: "inactiveMinutes > 30",
    cooldownMinutes: 60,
    proposedAction: "Automatisch ausloggen",
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },

  // ── Domain: stations ─────────────────────────────────────────────────────
  {
    id: "stations-01",
    code: "STATION_PING_PONG",
    domain: "stations",
    severity: "warn",
    trigger: "pattern",
    title: "Auftrag wird hin- und hergeschoben",
    description: "Auftrag heute mehr als 3× verschoben",
    expression: "stationMoves > 3",
    cooldownMinutes: 120,
    proposedAction: "Ist die Reihenfolge falsch geplant?",
    routeOnClick: "/warendurchlauf",
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "stations-02",
    code: "STATION_MISSING_PHOTO",
    domain: "stations",
    severity: "warn",
    trigger: "missing_data",
    title: "Station verschoben ohne Pflichtfoto",
    description: "Auftrag wurde weiterverschoben, aber das Foto fehlt",
    expression: "movedWithoutPhoto === true",
    cooldownMinutes: 30,
    proposedAction: "Foto jetzt nachholen",
    routeOnClick: "/warendurchlauf",
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "stations-03",
    code: "STATION_BLOCKED_RELEASE",
    domain: "stations",
    severity: "critical",
    trigger: "missing_data",
    title: "Ohne Freigabe weiterverschoben",
    description: "Auftrag wurde ohne Kundenfreigabe freigegeben",
    expression: "movedWithoutRelease === true",
    cooldownMinutes: 0,
    proposedAction: "Rückgängig machen",
    routeOnClick: "/warendurchlauf",
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },

  // ── Domain: payment ───────────────────────────────────────────────────────
  {
    id: "payment-01",
    code: "PAYMENT_OVERDUE_14D",
    domain: "payment",
    severity: "warn",
    trigger: "timeout",
    title: "Rechnung seit 14 Tagen offen",
    description: "Eine Rechnung ist 14 Tage ohne Zahlung",
    expression: "overduedays >= 14",
    cooldownMinutes: 1440,
    proposedAction: "Erinnerung versenden",
    routeOnClick: "/customers",
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "payment-02",
    code: "PAYMENT_OVERDUE_30D",
    domain: "payment",
    severity: "critical",
    trigger: "timeout",
    title: "Rechnung seit 30 Tagen überfällig",
    description: "Eine Rechnung ist 30 Tage ohne Zahlung — Mahnstufe fällig",
    expression: "overduedays >= 30",
    cooldownMinutes: 1440,
    proposedAction: "Mahnstufe 1 versenden",
    routeOnClick: "/customers",
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "payment-03",
    code: "PAYMENT_CUSTOMER_RISK",
    domain: "payment",
    severity: "warn",
    trigger: "threshold",
    title: "Kunde hat viele offene Rechnungen",
    description: "Mehr als 3 offene Rechnungen bei einem Kunden",
    expression: "openInvoiceCount > 3",
    cooldownMinutes: 720,
    proposedAction: "Neuen Auftrag freigeben?",
    routeOnClick: "/customers",
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },

  // ── Domain: data ─────────────────────────────────────────────────────────
  {
    id: "data-01",
    code: "DATA_REWORK_DOUBLED",
    domain: "data",
    severity: "warn",
    trigger: "drift",
    title: "Reklamationsquote stark gestiegen",
    description: "Reklamationsquote doppelt so hoch wie im Vormonat",
    expression: "reworkRate > lastMonthReworkRate * 2",
    cooldownMinutes: 1440,
    proposedAction: "Ursachenanalyse starten",
    routeOnClick: "/performance",
    isActive: true,
    requiredFeatureFlag: "warning_complaint",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "data-02",
    code: "DATA_DOCUMENTATION_DROP",
    domain: "data",
    severity: "warn",
    trigger: "drift",
    title: "Fotodokumentation sinkt",
    description: "Fotodokuquote unter 80 %",
    expression: "documentationRate < 0.8",
    cooldownMinutes: 720,
    proposedAction: "Werkstatt erinnern",
    routeOnClick: "/warendurchlauf",
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },

  // ── Domain: backup ────────────────────────────────────────────────────────
  {
    id: "backup-01",
    code: "BACKUP_STALE_36H",
    domain: "backup",
    severity: "critical",
    trigger: "timeout",
    title: "Backup veraltet",
    description: "Letztes erfolgreiches Backup älter als 36 Stunden",
    expression: "lastBackupAge > 36",
    cooldownMinutes: 120,
    proposedAction: "Manuelles Backup starten",
    routeOnClick: "/settings",
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },

  // ── Domain: hardware ─────────────────────────────────────────────────────
  {
    id: "hardware-01",
    code: "PRINTER_JOB_FAILED",
    domain: "hardware",
    severity: "warn",
    trigger: "threshold",
    title: "Druckauftrag fehlgeschlagen",
    description: "Ein Druckauftrag konnte nicht verarbeitet werden",
    expression: "printJobFailed === true",
    cooldownMinutes: 15,
    proposedAction: "Drucker prüfen",
    routeOnClick: "/settings",
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "hardware-02",
    code: "DEVICE_OFFLINE_24H",
    domain: "hardware",
    severity: "info",
    trigger: "timeout",
    title: "Gerät nicht erreichbar",
    description: "Ein Gerät war länger als 24 Stunden offline",
    expression: "deviceOfflineHours > 24",
    cooldownMinutes: 360,
    proposedAction: "Verbindung prüfen",
    routeOnClick: "/settings",
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },

  // ── Domain: customer ─────────────────────────────────────────────────────
  {
    id: "customer-01",
    code: "CUSTOMER_OPEN_OVER_LIMIT",
    domain: "customer",
    severity: "warn",
    trigger: "threshold",
    title: "Offene Forderungen über Limit",
    description: "Offene Forderungen übersteigen das Kundenlimit",
    expression: "openAmount > customerWarnLimit",
    cooldownMinutes: 720,
    proposedAction: "Auftragsfreigabe prüfen",
    routeOnClick: "/customers",
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "customer-02",
    code: "CUSTOMER_NO_CONTACT_DETAILS",
    domain: "customer",
    severity: "info",
    trigger: "missing_data",
    title: "Fehlende Kontaktdaten",
    description: "Kunde hat weder E-Mail noch Telefonnummer",
    expression: "missingContact === true",
    cooldownMinutes: 1440,
    proposedAction: "Kontakt nachpflegen",
    routeOnClick: "/customers",
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },

  // ── Domain: upload ────────────────────────────────────────────────────────
  {
    id: "upload-01",
    code: "UPLOAD_MISSING_CATEGORY",
    domain: "upload",
    severity: "warn",
    trigger: "missing_data",
    title: "Datei ohne Kategorie",
    description: "Eine hochgeladene Datei hat keine Kategorie",
    expression: "fileWithoutCategory === true",
    cooldownMinutes: 60,
    proposedAction: "Kategorie nachtragen",
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },

  // ── Domain: privacy ────────────────────────────────────────────────────────
  {
    id: "privacy-01",
    code: "DSR_DEADLINE_NEAR",
    domain: "privacy",
    severity: "info",
    trigger: "timeout",
    title: "Datenschutzanfrage läuft bald ab",
    description: "Auskunfts- oder Löschanfrage hat weniger als 5 Tage bis Deadline",
    expression: "dsrDaysLeft < 5",
    cooldownMinutes: 720,
    proposedAction: "Bearbeitung einplanen",
    routeOnClick: "/settings/dsr",
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },

  // ── Domain: search ────────────────────────────────────────────────────────
  {
    id: "search-01",
    code: "SEARCH_NO_RESULT_RATE_HIGH",
    domain: "search",
    severity: "info",
    trigger: "drift",
    title: "Hohe Nullsuch-Rate",
    description: "Mehr als 20 % der Suchen liefern keine Treffer",
    expression: "noResultRate > 0.2",
    cooldownMinutes: 1440,
    proposedAction: "Synonymliste oder Index prüfen",
    isActive: true,
    createdAt: now,
    updatedAt: now,
  },
];
