// src/lib/search/actionRegistry.ts
// Aktionsverzeichnis für Intent-Erkennung in der globalen Suche
import type { SearchAction } from "@/types/search";

export const SEARCH_ACTIONS: SearchAction[] = [
  {
    id: "action-new-order",
    code: "ACTION_CREATE_ORDER",
    label: "Neuen Auftrag anlegen",
    synonyms: ["auftrag erstellen", "auftrag neu", "wareneingang", "neuer auftrag", "order"],
    routeOnSelect: "/orders/new",
    icon: "📋",
    description: "Direkt zum Auftragsanlage-Wizard",
  },
  {
    id: "action-scan",
    code: "ACTION_SCAN",
    label: "Foto-Scan starten",
    synonyms: ["scan", "foto", "kamera", "ocr", "barcode", "dokument scannen", "einscannen"],
    routeOnSelect: "/scan",
    icon: "📷",
    description: "Kamera öffnen und Dokument erfassen",
  },
  {
    id: "action-new-customer",
    code: "ACTION_CREATE_CUSTOMER",
    label: "Neuen Kunden anlegen",
    synonyms: ["kunde anlegen", "kunde erstellen", "neuer kunde", "kundenkarte", "kundenanlage"],
    routeOnSelect: "/customers/new",
    icon: "👤",
    description: "Kundenstammdaten erfassen",
  },
  {
    id: "action-invoice",
    code: "ACTION_CREATE_INVOICE",
    label: "Rechnung schreiben",
    synonyms: ["rechnung erstellen", "abrechnen", "fakturieren", "invoice", "rechnung ausstellen", "rechnung stellen"],
    routeOnSelect: "/orders?filter=billable",
    icon: "🧾",
    description: "Zu abrechenbaren Aufträgen",
  },
  {
    id: "action-warendurchlauf",
    code: "ACTION_WARENDURCHLAUF",
    label: "Warendurchlauf öffnen",
    synonyms: ["werkstatt", "produktion", "durchlauf", "status board", "stationen", "leitstand"],
    routeOnSelect: "/warendurchlauf",
    icon: "🏭",
    description: "Aktuelle Werkstattlage",
  },
  {
    id: "action-customers",
    code: "ACTION_CUSTOMERS",
    label: "Kundenkartei öffnen",
    synonyms: ["kunden", "kundenliste", "kundenkartei", "adressen"],
    routeOnSelect: "/customers",
    icon: "👥",
    description: "Alle Kunden suchen und verwalten",
  },
  {
    id: "action-lager",
    code: "ACTION_LAGER",
    label: "Lager & Badregelkarte",
    synonyms: ["lager", "material", "bestand", "bad", "bäder", "chemikalien", "säure", "kupfer"],
    routeOnSelect: "/items",
    icon: "📦",
    description: "Lagerbestände und Badwerte",
  },
  {
    id: "action-settings",
    code: "ACTION_SETTINGS",
    label: "Einstellungen öffnen",
    synonyms: ["einstellungen", "settings", "konfiguration", "drucker", "benutzer", "nutzer"],
    routeOnSelect: "/settings",
    icon: "⚙️",
    description: "App-Konfiguration",
  },
  {
    id: "action-performance",
    code: "ACTION_PERFORMANCE",
    label: "Performance Cockpit",
    synonyms: ["performance", "auswertung", "kpi", "statistik", "umsatz", "durchlaufzeit"],
    routeOnSelect: "/performance",
    icon: "📊",
    description: "Kennzahlen und Auswertungen",
  },
  {
    id: "action-overdue",
    code: "ACTION_OVERDUE",
    label: "Überfällige Rechnungen",
    synonyms: ["mahnung", "überfällig", "offen", "rückstand", "zahlungsverzug"],
    routeOnSelect: "/orders?filter=overdue",
    icon: "⚠️",
    description: "Aufträge mit überfälligen Zahlungen",
  },
];
