// src/lib/search/actionRegistry.ts
// Aktionsverzeichnis für Intent-Erkennung in der globalen Suche
import type { SearchAction } from "@/types/search";

export const SEARCH_ACTIONS: SearchAction[] = [
  {
    id: "action-new-order",
    code: "ACTION_CREATE_ORDER",
    label: "Neuen Auftrag anlegen",
    synonyms: ["auftrag erstellen", "auftrag neu", "wareneingang", "neuer auftrag", "order"],
    routeOnSelect: "/orders/new",
    icon: "📋",
    description: "Direkt zum Auftragsanlage-Wizard",
  },
  {
    id: "action-scan",
    code: "ACTION_SCAN",
    label: "Foto-Scan starten",
    synonyms: ["scan", "foto", "kamera", "ocr", "barcode", "dokument scannen", "einscannen"],
    routeOnSelect: "/scan",
    icon: "📷",
    description: "Kamera öffnen und Dokument erfassen",
  },
  {
    id: "action-new-customer",
    code: "ACTION_CREATE_CUSTOMER",
    label: "Neuen Kunden anlegen",
    synonyms: ["kunde anlegen", "kunde erstellen", "neuer kunde", "kundenkarte", "kundenanlage"],
    routeOnSelect: "/customers/new",
    icon: "👤",
    description: "Kundenstammdaten erfassen",
  },
  {
    id: "action-invoice",
    code: "ACTION_CREATE_INVOICE",
    label: "Rechnung schreiben",
    synonyms: ["rechnung erstellen", "abrechnen", "fakturieren", "invoice", "rechnung ausstellen", "rechnung stellen"],
    routeOnSelect: "/buchhaltung/rechnungen/neu",
    icon: "🧾",
    description: "Neue Rechnung im angebundenen Buchhaltungsbereich",
  },
  {
    id: "action-warendurchlauf",
    code: "ACTION_WARENDURCHLAUF",
    label: "Warendurchlauf öffnen",
    synonyms: ["werkstatt", "produktion", "durchlauf", "status board", "stationen", "leitstand"],
    routeOnSelect: "/warendurchlauf",
    icon: "🏭",
    description: "Aktuelle Werkstattlage",
  },
  {
    id: "action-customers",
    code: "ACTION_CUSTOMERS",
    label: "Kundenkartei öffnen",
    synonyms: ["kunden", "kundenliste", "kundenkartei", "adressen"],
    routeOnSelect: "/customers",
    icon: "👥",
    description: "Alle Kunden suchen und verwalten",
  },
  {
    id: "action-lager",
    code: "ACTION_LAGER",
    label: "Lager & Badregelkarte",
    synonyms: ["lager", "material", "bestand", "bad", "bäder", "chemikalien", "säure", "kupfer", "labor", "laboranalyse", "badanalyse"],
    routeOnSelect: "/items",
    icon: "📦",
    description: "Lagerbestände und Badwerte",
  },
  {
    id: "action-settings",
    code: "ACTION_SETTINGS",
    label: "Einstellungen öffnen",
    synonyms: ["einstellungen", "settings", "konfiguration", "drucker", "benutzer", "nutzer"],
    routeOnSelect: "/settings",
    icon: "⚙️",
    description: "App-Konfiguration",
  },
  {
    id: "action-performance",
    code: "ACTION_PERFORMANCE",
    label: "Performance Cockpit (Analyse)",
    synonyms: ["performance", "auswertung", "kpi", "statistik", "umsatz", "durchlaufzeit", "analyse", "analysen"],
    routeOnSelect: "/performance",
    icon: "📊",
    description: "Kennzahlen und Auswertungen",
  },
  {
    id: "action-overdue",
    code: "ACTION_OVERDUE",
    label: "Überfällige Rechnungen",
    synonyms: ["mahnung", "überfällig", "offen", "rückstand", "zahlungsverzug"],
    routeOnSelect: "/buchhaltung/rechnungen?ueberfaellig=1",
    icon: "⚠️",
    description: "Serverseitig gefilterte überfällige Rechnungen",
  },
  {
    id: "action-home",
    code: "ACTION_HOME",
    label: "Startseite (Home)",
    synonyms: ["home", "start", "heute", "dashboard", "tagesübersicht", "kommende arbeiten", "startseite"],
    routeOnSelect: "/",
    icon: "🏠",
    description: "Zurück zur Hauptübersicht",
  },
  {
    id: "action-wareneingang",
    code: "ACTION_WARENEINGANG",
    label: "Wareneingang",
    synonyms: ["annahme", "intake", "eingang", "kamera", "scan", "foto", "erfassen", "neuer auftrag", "wareneingang"],
    routeOnSelect: "/warendurchlauf/wareneingang",
    icon: "📥",
    description: "Wareneingang & Erfassung",
  },
  {
    id: "action-galvanik",
    code: "ACTION_GALVANIK",
    label: "Galvanik",
    synonyms: ["galvanik", "bäder", "bad", "beschichtung", "verchromen", "vernickeln", "versilbern", "vergolden", "brünieren", "werkstatt"],
    routeOnSelect: "/warendurchlauf/galvanik",
    icon: "🧪",
    description: "Galvanik & Produktion",
  },
  {
    id: "action-warenausgang",
    code: "ACTION_WARENAUSGANG",
    label: "Warenausgang",
    synonyms: ["versand", "abholung", "fertig", "ausgang", "paket", "tracking", "lieferschein", "warenausgang"],
    routeOnSelect: "/warendurchlauf/warenausgang",
    icon: "📤",
    description: "Warenausgang & Versand",
  },
  {
    id: "action-orders",
    code: "ACTION_ORDERS",
    label: "Aufträge",
    synonyms: ["auftrag", "aufträge", "auftragsbuch", "vorgang", "order", "frist", "status", "termin", "laufkarte"],
    routeOnSelect: "/orders",
    icon: "📋",
    description: "Alle Aufträge verwalten",
  },
  {
    id: "action-kommunikation",
    code: "ACTION_KOMMUNIKATION",
    label: "Kommunikation (Telefonnotizen)",
    synonyms: ["kommunikation", "telefon", "telefonnotiz", "anruf", "rückruf", "nachricht", "email", "gespräch"],
    routeOnSelect: "/kommunikation",
    icon: "📞",
    description: "Zentrale Kommunikation",
  },
  {
    id: "action-kalender",
    code: "ACTION_KALENDER",
    label: "Kalender",
    synonyms: ["kalender", "termin", "termine", "frist", "wiedervorlage", "datum", "planung"],
    routeOnSelect: "/kalender",
    icon: "📅",
    description: "Termine & Fristen",
  },
  {
    id: "action-buchhaltung",
    code: "ACTION_BUCHHALTUNG",
    label: "Buchhaltung",
    synonyms: ["buchhaltung", "finanzen", "rechnung", "rechnungen", "beleg", "belege", "datev", "lexware", "export"],
    routeOnSelect: "/buchhaltung",
    icon: "💶",
    description: "Finanz-Dashboard",
  },
  {
    id: "action-zahlung",
    code: "ACTION_ZAHLUNG",
    label: "Zahlungsbereich",
    synonyms: ["zahlungsstatistik", "zahlung", "zahlungen", "offen", "bezahlt", "mahnung", "offene posten", "zahlungsmoral"],
    routeOnSelect: "/buchhaltung/zahlung",
    icon: "💰",
    description: "Zahlungseingänge & OP-Liste",
  },
  {
    id: "action-admin",
    code: "ACTION_ADMIN",
    label: "Admin & Testanalyse",
    synonyms: ["admin", "developer", "import", "geräte", "lizenzen", "testanalyse", "analytics", "analyse der app", "system"],
    routeOnSelect: "/admin/analytics",
    icon: "🛡️",
    description: "Systemverwaltung",
  }
];
