// src/lib/customerType/registry.ts
// Konfigurationstabelle für alle Kundentypen — editierbar in Einstellungen
import type { CustomerTypeConfig, CustomerType } from "@/types/customerType";

export const CUSTOMER_TYPE_REGISTRY: Record<CustomerType, CustomerTypeConfig> = {
  private: {
    type: "private",
    label: "Privatkunde",
    taxBehavior: "b2c",
    requiresXRechnung: false,
    defaultDiscountPercent: 0,
    allowsCustomQuoting: false,
    defaultCommunicationChannel: "email",
    requiresExtendedDocumentation: false,
    paymentTermDays: 14,
    dunningLevelMax: 2,
    warnIfOpenAmountAbove: 500,
  },
  business: {
    type: "business",
    label: "Gewerbekunde",
    taxBehavior: "b2b",
    requiresXRechnung: true,
    defaultDiscountPercent: 0,
    allowsCustomQuoting: true,
    defaultCommunicationChannel: "email",
    requiresExtendedDocumentation: false,
    paymentTermDays: 30,
    dunningLevelMax: 3,
    warnIfOpenAmountAbove: 2000,
  },
  oldtimer_fan: {
    type: "oldtimer_fan",
    label: "Oldtimer-Liebhaber",
    taxBehavior: "b2c",
    requiresXRechnung: false,
    defaultDiscountPercent: 0,
    allowsCustomQuoting: true,
    defaultCommunicationChannel: "phone",
    requiresExtendedDocumentation: true,
    paymentTermDays: 14,
    dunningLevelMax: 1,
    warnIfOpenAmountAbove: 1500,
  },
  art_furniture: {
    type: "art_furniture",
    label: "Möbel & Kunst",
    taxBehavior: "b2c",
    requiresXRechnung: false,
    defaultDiscountPercent: 0,
    allowsCustomQuoting: true,
    defaultCommunicationChannel: "email",
    requiresExtendedDocumentation: true,
    paymentTermDays: 14,
    dunningLevelMax: 1,
    warnIfOpenAmountAbove: 1500,
  },
  regular: {
    type: "regular",
    label: "Stammkunde",
    taxBehavior: "b2b",
    requiresXRechnung: true,
    defaultDiscountPercent: 5,
    allowsCustomQuoting: true,
    defaultCommunicationChannel: "email",
    requiresExtendedDocumentation: false,
    paymentTermDays: 30,
    dunningLevelMax: 3,
    warnIfOpenAmountAbove: 3000,
  },
};
