INSERT INTO konto (tenant_id, nummer, bezeichnung, kategorie, ist_erfolgskonto) VALUES
('galvanik-kreile', '8400', 'Erlöse Galvanikleistung 19%', 'erloes', true),
('galvanik-kreile', '8401', 'Erlöse Schleif-/Polierarbeiten 19%', 'erloes', true),
('galvanik-kreile', '8402', 'Erlöse Restauration / Sonderarbeit 19%', 'erloes', true),
('galvanik-kreile', '8410', 'Erlöse Materialweiterberechnung 19%', 'erloes', true),
('galvanik-kreile', '8736', 'Erlösminderung Skonto', 'erloesminderung', true),
('galvanik-kreile', '8740', 'Erlösminderung Reklamation/Gutschrift', 'erloesminderung', true),
('galvanik-kreile', '3400', 'Wareneingang Chemie', 'wareneinsatz', true),
('galvanik-kreile', '3401', 'Wareneingang Verbrauchsmaterial', 'wareneinsatz', true),
('galvanik-kreile', '3402', 'Wareneingang Verpackung', 'wareneinsatz', true),
('galvanik-kreile', '4120', 'Bruttolöhne', 'personal', true),
('galvanik-kreile', '4130', 'Gehälter', 'personal', true),
('galvanik-kreile', '4140', 'Geschäftsführergehalt', 'personal', true),
('galvanik-kreile', '4240', 'Gas, Strom, Wasser', 'energie', true),
('galvanik-kreile', '4242', 'Abwasser / Abfall', 'energie', true),
('galvanik-kreile', '4200', 'Raumkosten / Miete', 'sachkosten', true),
('galvanik-kreile', '4360', 'Versicherungen', 'sachkosten', true),
('galvanik-kreile', '4910', 'Bürobedarf', 'sachkosten', true),
('galvanik-kreile', '4920', 'Telefon / Internet', 'sachkosten', true),
('galvanik-kreile', '4930', 'Porto', 'sachkosten', true),
('galvanik-kreile', '4810', 'Reparatur / Instandhaltung', 'sachkosten', true),
('galvanik-kreile', '4830', 'Wartung Anlagen / Bäder', 'sachkosten', true),
('galvanik-kreile', '4670', 'Werbung', 'sachkosten', true),
('galvanik-kreile', '4710', 'Berufsgenossenschaft', 'sachkosten', true),
('galvanik-kreile', '4720', 'Sonstige Personalkosten', 'personal', true),
('galvanik-kreile', '4832', 'Abschreibungen', 'abschreibung', true),
('galvanik-kreile', '1576', 'Vorsteuer 19%', 'steuer', false),
('galvanik-kreile', '1776', 'Umsatzsteuer 19%', 'steuer', false),
('galvanik-kreile', '1200', 'Bank', 'bank', false),
('galvanik-kreile', '1000', 'Kasse', 'kasse', false),
('galvanik-kreile', '1360', 'Geldtransit', 'kasse', false),
('galvanik-kreile', '1400', 'Forderungen', 'forderung', false),
('galvanik-kreile', '1600', 'Verbindlichkeiten', 'verbindlichkeit', false)
ON CONFLICT (tenant_id, nummer) DO NOTHING;
